import { perroStoriesFromWp } from "./perroStories.wp";

export type Dog = {
  slug: string;
  name: string;
  age: string;
  size: string;
  sex?: string;
  weight?: string;
  tagline?: string;
  storyLeft: string;
  storyRight: string;
  profileUrl: string;
  /** Official photo URL (e.g. from grupoayudabodegueros.org media) */
  photoUrl?: string;
  /** Bullets for “Se entrega…” on the Mi historia page */
  deliveryChecklist?: readonly string[];
  /** Optional URL for Eva's voice — add when files are ready */
  audioUrl?: string;
  /** Muestra este emoji en el círculo en lugar de la foto (plantillas) */
  emojiAvatar?: string;
};

const profile = (slug: string) => `https://grupoayudabodegueros.org/perro/${slug}/`;

type PerroSlug = keyof typeof perroStoriesFromWp;

function wp(slug: PerroSlug) {
  return perroStoriesFromWp[slug];
}

/**
 * Dog metadata + photos; “Mi historia” text comes from WordPress REST
 * (`perroStoriesFromWp`, generated by scripts/sync-perro-from-wp.mjs).
 */
const featured: Dog[] = [
  {
    slug: "rodolfo",
    name: "Rodolfo",
    age: "2 años",
    size: "Mediano",
    sex: "Macho",
    weight: "11 kg",
    tagline: "Bodeguero Andaluz en busca de familia",
    profileUrl: profile("rodolfo"),
    photoUrl:
      "https://grupoayudabodegueros.org/wp-content/uploads/2026/04/MOLLET-DEL-VALLES-4.png",
    ...wp("rodolfo"),
  },
  {
    slug: "piula",
    name: "Piula",
    age: "8 años",
    size: "Pequeña",
    sex: "Hembra",
    weight: "6,5 kg",
    tagline: "Alma de cachorra en cuerpo adulto",
    profileUrl: profile("piula"),
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2026/04/MOLLET-DEL-VALLES-3.png",
    ...wp("piula"),
  },
  {
    slug: "atenea",
    name: "Atenea",
    age: "2 años",
    size: "Mediano",
    sex: "Hembra",
    weight: "10,45 kg",
    tagline: "Mamá que ya cuidó a sus cachorros",
    profileUrl: profile("atenea"),
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2026/03/MOLLET-DEL-VALLES.png",
    ...wp("atenea"),
  },
];

const others: Omit<Dog, "storyLeft" | "storyRight" | "profileUrl" | "deliveryChecklist">[] = [
  {
    slug: "amapola",
    name: "Amapola",
    age: "4 meses",
    size: "Pequeña",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2026/03/IMG_0898-1.jpeg",
  },
  {
    slug: "toni",
    name: "Toni",
    age: "1 año 3 meses",
    size: "Pequeña",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2026/02/IMG_0115-768x603.jpeg",
  },
  {
    slug: "aretha",
    name: "Aretha",
    age: "10 años",
    size: "Mediana",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/12/IMG_8891-768x1024.jpeg",
  },
  {
    slug: "lucho",
    name: "Lucho",
    age: "10 años",
    size: "Mediano",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/12/IMG_7657-1-768x672.jpeg",
  },
  {
    slug: "atila",
    name: "Atila",
    age: "8 años",
    size: "Mediano",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/11/IMG_6651-768x627.jpeg",
  },
  {
    slug: "huno",
    name: "Huno",
    age: "6 años 3 meses",
    size: "Pequeño",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/09/huno-768x576.webp",
  },
  {
    slug: "hache",
    name: "Hache",
    age: "2 años 10 meses",
    size: "Pequeño",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/09/hache-768x576.webp",
  },
  {
    slug: "grecia",
    name: "Grecia",
    age: "3 años 9 meses",
    size: "Mediana",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/09/grecia-768x576.webp",
  },
  {
    slug: "juliet",
    name: "Juliet",
    age: "4 años",
    size: "Mediano",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/09/juliet-768x577.webp",
  },
  {
    slug: "amaia",
    name: "Amaia",
    age: "4 años 3 meses",
    size: "Pequeño",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/09/amaia.webp",
  },
  {
    slug: "leia",
    name: "Leia",
    age: "3 años 6 meses",
    size: "Mediano",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/09/leia.webp",
  },
  {
    slug: "gordi",
    name: "Gordi",
    age: "Adulto",
    size: "Pequeño",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/08/gordi.webp",
  },
  {
    slug: "lala",
    name: "Lala",
    age: "15 años",
    size: "Pequeño",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/08/lala.webp",
  },
  {
    slug: "waha",
    name: "Waha",
    age: "8 años 4 meses",
    size: "Mediano",
    photoUrl: "https://grupoayudabodegueros.org/wp-content/uploads/2025/08/waha.webp",
  },
];

const othersAsDogs: Dog[] = others.map((d) => ({
  ...d,
  tagline: "Historias del refugio GAB",
  profileUrl: profile(d.slug),
  ...wp(d.slug as PerroSlug),
}));

export const dogs: Dog[] = [...featured, ...othersAsDogs];
